export const Footer2 = () => {
  return (
    <div className="footer2">
      <div>
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-ssl.png"
          alt=""
        />

        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-visa.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-mc.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-ae.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-ae.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-nb.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-cod.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-rupay.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-paypal.png"
          alt=""
        />
        <img
          src="https://constant.myntassets.com/checkout/assets/img/footer-bank-bhim.png"
          alt=""
        />
      </div>
    </div>
  );
};
